apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
	app: grafana
  ports:
	- protocol: TCP
  	port: 3000  # The port exposed inside the cluster
  	targetPort: 3000  # The port Grafana listens on
  type: LoadBalancer
