apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
	global:
  	scrape_interval: 15s
  	evaluation_interval: 15s

	scrape_configs:
  	- job_name: 'jenkins'
    	static_configs:
      	- targets: ['10.111.74.88:8080']  # Replace with your Jenkins Service IP and Port
        	labels:
          	instance: 'jenkins'
    	metrics_path: /prometheus
